# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - calculator-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://calculatorappregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c2bc44dea35c42b6bef12e9b4f131c07 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_18e3f70c49a64cbd94ad4aef39586b68 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: calculatorappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c2bc44dea35c42b6bef12e9b4f131c07 }}/calculatorappregistry.azurecr.io:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'calculator-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3523f0c0af59431bace5ab109af28677 }}
        images: 'calculatorappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c2bc44dea35c42b6bef12e9b4f131c07 }}/calculatorappregistry.azurecr.io:${{ github.sha }}'